language: ruby
sudo: required
rvm:
- 2.4.1
addons:
  ssh_known_hosts: alexanderweinert.net
stages:
  name: deploy
  if: repo = aweinert/website and branch = ci-deploy and env(RSYNC_HOST) is set and
    env(RSYNC_PASSWORD) is set
install: gem install jekyll jekyll-scholar html-proofer
script:
- jekyll b
- htmlproofer --allow-hash-href --empty-alt-ignore --only-4xx _site
before_deploy:
- openssl aes-256-cbc -K $encrypted_5a768c84c6ed_key -iv $encrypted_5a768c84c6ed_iv
  -in alexanderweinert.net.enc -out alexanderweinert.net -d
- eval "$(ssh-agent -s)"
- chmod 600 alexanderweinert.net
- ssh-add alexanderweinert.net
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r -v _site/ alexanderweinert.net:/www/
  on:
    branch: ci-deploy
