language: ruby
rvm:
- 2.4.1
stages:
  name: deploy
  if: repo = aweinert/website and branch = ci-deploy and env(RSYNC_HOST) is set and
    env(RSYNC_PASSWORD) is set
install: gem install jekyll jekyll-scholar html-proofer
script:
- jekyll b
- htmlproofer --allow-hash-href --empty-alt-ignore --only-4xx _site
deploy:
  provider: script
  skip_cleanup: true
  script: cd _site ; find . -type f -exec curl --verbose --user $FTP_USER:$FTP_PASSWORD
    --ftp-create-dirs -T {} $FTP_HOST/\{\} \;
  on:
    branch: ci-deploy
env:
  global:
  - secure: IHHA7X83cpm5toKBHsj2DjXOz35rD8+MVkpobfacuJJ5LAZg9RjYn96bkCCgUCIjYbHL6z/l2QtO0cAK4VupKkaV9P5mUQ31zR9kYFbjV42DbagnfEn+rwhNGsz2AaaHmRS6SaFrVAQUUKNbrTfpi9nt24f3I9tUHMpMo8iUqLfITiU3EZ3CvfgXnx4fd8e5C3Rj39GZ9DN2gulPblydn+uhaInNyark7trHEiU9qhxCGF/JaKY1Dd6syF/0JIpSbOy4hgkif+duWsmTPieBhKHnWLgWyZ6URtkuKHCof1sUpY8UM49X73S81vbRncBGKAI50/2mJDRNBmLe8VwkgglegXnnLbPYHmkqhI88A/EcyWLmBqjR3QPRBvdvNwvWGQ1V0G4plIf9c2y2ao5UQNm6D2lom3ro8Y+2lGHXkGcsmXPlRPClmBI66S67yJ/0ifRIN9rQpVjTbPE5/YYDMXX+VXXj2gnBx7k8DpyTe7BhgcsQFUQ2Nt0ahTujzvMxw9LdBbaNM6sRu++zt4r+rOkrQlXIR/SR0xLBUWHNT4ukCDC3fev2GULMMLxQQboOPlgDjI11aKuqJtJky3jfIsYpsCuKqgQk6zE2e/dyKx+QuHVZapO2UjlxukdM0UFKNAZa/tWwwDvOEphPR75kyeZQOriZNkQQMGoUK9elR5k=
  - secure: AfoU1GQGOFQm6DOhciN7u+cWopAZ1dV7UtmX6goWLhC+17NKjLfJC1xe6BdSlVYX1YPIppdzmDqA+ApLrLq/PR/qIjT7r633udQd7fzOadJHjy1+RO6FG2hqxBs6KWCoisKp7onsQpEI4ulzFH+J2LpBmWefZn6RS5A9JGcsLU3JFT6YbTpl5ymS+ZVbAx45lVFqWGMIUIpyOQr+43WWyefvXX3mcVFVao3V5NCnT5jKhF/8r0OHV6Wc2FGEPH28ptIYL29o9NLuJUoFzxqQmHb9/OFSioDvJ/ace3UyYxMOWZirHO7KY2F7y+UvCRc4DSSm/UkHxsSv7UW/g8tNb9ULCXoHvU58A1Z9rQ+lBYVO79eOeaQpqizjcQD7hiruE9KgX5e6IzfRt79zGUBZ7tdIQMu95x4k7gVcyGQIk9QPj94Hx5v7bEC3ec1GH31gfyN5DKgg/9C1L6e+S8Z6CLDVhBAnEw7OqmFpUsUrbk5sEYXM4PguIJIhkX6+D10LxVtYzuOkjGgV1VkHvvloH1kHEjGeoHjMJGRfAdEjLEbXmjwiYK+3KiJKLAA+EmpN4GfKovKTvQWzyFCGT6urg6li2DNQcBVO3RUXv4Rw4Gc6Izofew/hSxsF4Ni7aQGL168x41b0Uwmr99GVzx1nzDft2bhhPOkH3bEiQJ8KlwE=
  - secure: TfmmU0JVgtg5EDI/g1Kb8/QSs49Bqv9fNXWBHUH9Em570r/wr4OxxGnOve7UehwO7qKGaoQeO+EGWikCKDfdDcVP4xkv49EhIbTJibnCNRyh/yPMBO+zVZrOmZmTDZMpSMn1drtfUhBxnEVWhJQJB6iWYBIPjsB8K7IBmslkvU2NjYMD9hSomOocZfDL4IQm4vrJxpqIwGScLLZC++442g3eTT4ha2snfW+CVhmGx26/xU7WA8nrCGLZtrlJSuYP9NUbzNdZ02/nI7XvZurC8j7d1yZw4KU375TuWlEO0M1T6rafZK+Aux2D5DOH/Cah6smiy4dehk9G0CBs8FlJx3JeOPAGNh04lBrGVnwNIeIBbDXWZ2O/SlZtchaDuqVQd61SD0ZvfHG1f83/yj23KO+DiYtcUdp5aD9vh0pDjrZcOh9hGoVy2hOmP3LZbbM58qsIWRBlSplILxCYOtz+pBbRWzpA6w4UB7TqsLQWj+3Q9FdJwt/mc8f/ftoLuw3E64Y4caQpf5jqFvmXNOxc90IAnYDDOUSzSPHbTa+OXPiTyTwnvnUpCPPzo841hOX9WTCXLHHJckhAcIsPH7KBHgYNYDT4NYgYMP0OMHx4kAkWSX5C98ZJqJk4V/snYXW/MXu6WSYIK/z/4EkfaBWtSBQO50uEiBv24NEjKvotky8=
