# Site settings
title: Alexander Weinert
email: contact@alexanderweinert.net
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alexanderweinert.net" # the base hostname & protocol for your site
github_username:  aweinert

# Build settings
markdown: kramdown
