defaults: &defaults
  working_directory: ~/repo
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - run:
          name: Rsync Install
          command: sudo apt-get install rsync
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile.lock" }}
            - rubygems-v1-fallback
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: rubygems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - run:
          name: Htmlproofer
          command: bundle exec htmlproofer --allow-hash-href --empty-alt-ignore --only-4xx _site
      - add_ssh_keys
      - run:
          name: Deploy
          command: rsync -4 -vvvv -r _site/ alexanderweinert.net@alexanderweinert.net:/www/
      - persist_to_workspace:
          root: ./
          paths:
            - _site
